[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18"
  functions = "netlify/functions"

[build.environment]
  VITE_SUBMIT_URL = "/.netlify/functions/submit"
  APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbw29TxNEwm0ATk9DxeXcbj9eyHEY58tHexqZm3r_Sp94gkaWe6sK7G5zjXS8RQ3qGaqCQ/exec"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUBMIT_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200